inveniosoftware/invenio-logging

invenio_logging/fs.py
invenio_logging/sentry.py

* Removes some unused imports.
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

global: unused imports

---

tests/test_invenio_logging.py

Signed-off-by: Bruno Cuc <bruno.cuc@cern.ch>

global: new tests, increased coverage

---

invenio_logging/sentry.py
invenio_logging/sentry6.py
setup.py
tests/test_sentry.py

* Adds support for overriding the default Sentry extension class, so
that custom behavior can be added.
* Adds support for using Raven 5.0.0 and Sentry 6.x.
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

sentry: custom extension class

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_logging/version.py

Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

release: v1.0.0a2

---

invenio_logging/version.py

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

version: post-release bump

---

.travis.yml
invenio_logging/sentry.py
tests/test_sentry.py

* Adds compatibility mode for raven==5.1.0
Signed-off-by: Mihai Bivol <mihai.bivol@cern.ch>

global: compatibiliy mode for raven==5.1.0

---

AUTHORS.rst
CHANGES.rst
RELEASE-NOTES.rst
invenio_logging/version.py

Signed-off-by: Mihai Bivol <mihai.bivol@cern.ch>

release: v1.0.0a3

---

AUTHORS.rst
examples/app.py
tests/test_examples_app.py

* Adds test_examples_app.py. (closes #21)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

tests: addition of test_examples_app.py

---

CHANGES.rst
README.rst
RELEASE-NOTES.rst
invenio_logging/version.py

Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

release: v1.0.0b1

---

invenio_logging/sentry.py

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

sentry: properly initialize handler

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_logging/version.py

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

release: v1.0.0b3

---

.travis.yml

traivs: remove pypy from test matrix

---

invenio_logging/config.py
invenio_logging/console.py
invenio_logging/fs.py
invenio_logging/sentry.py
invenio_logging/utils.py
tests/test_sentry.py

* If request_id is set in flask.g, add it to log record.
Closes #41
Co-Authored-By: Alexander Ioannidis <a.ioannidis@cern.ch>

global: adding request_id in log record

---

invenio_logging/sentry.py
setup.py
tests/conftest.py
tests/test_sentry.py

sentry: fix warnings being incorrectly logged

---

invenio_logging/__init__.py

docs: fix code check

---

invenio_logging/config.py
invenio_logging/sentry.py
setup.py
tests/test_sentry.py

sentry:  move from raven to sentry-python

---

CHANGES.rst
invenio_logging/version.py

release: v1.2.0

---

CHANGES.rst
docs/conf.py
invenio_logging/__init__.py
invenio_logging/version.py
setup.py

caused version conflicts with other invenio-modules

global: bump minimal six version

---

invenio_logging/fs.py

Fix typo in fs.py

---

invenio_logging/sentry.py
pytest.ini
run-tests.sh
tests/test_sentry.py

Addresses inveniosoftware/opensource#65

isort fixing

---

docs/conf.py
invenio_logging/config.py
invenio_logging/sentry.py
setup.py

* Adds SQLAlchemy integration:
https://docs.sentry.io/platforms/python/configuration/integrations/sqlalchemy/
* Adds REDIS integration:
https://docs.sentry.io/platforms/python/configuration/integrations/redis/
* Closes #62

sentry: REDIS SQLAlchemy integretion

---

CHANGES.rst
invenio_logging/__init__.py
setup.cfg

- **installation: upper pin Sentry-SDK**
- **📦 release: v2.1.1**

Pin Sentry-SDK and release v2.1.1

---

.github/workflows/pypi-publish.yml
.github/workflows/tests.yml
CHANGES.rst
invenio_logging/__init__.py
setup.cfg

- setup: pin dependencies
- setup: change to reusable workflows
- release: v2.1.2

pin dependencies

---

CHANGES.rst
invenio_logging/__init__.py
setup.cfg

- setup: change sentry_sdk to sentry
- release: v2.2.0

fix sentry

---

CHANGES.rst
invenio_logging/__init__.py
setup.cfg

- setup: bump invenio dependencies
- release: v3.0.0

bump major

---

invenio_logging/ext.py

* closes https://github.com/inveniosoftware/invenio-jobs/issues/67
:heart: Thank you for your contribution!

ext: add DEBUG as default logger level
